### ISSUE TITLE
infrastructure/gateway could not startup

### ISSUE THREAD

**Issue by blling** [hdimitrieski/e-shop#7]
When i startup the gateway:
```shell
java -DEUREKA_USER=user -DCONFIG_SERVICE_USER=user -DCONFIG_SERVICE_PASSWORD=cfg-password -jar gateway.jar --spring.profiles.active=docker
```

fail with the error:
```shell
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-07-01 14:45:57.514 ERROR [api-gateway,,] 291475 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    reactor.netty.transport.ServerTransport$DisposableBind.<init>(ServerTransport.java:494)

The following method did not exist:

    'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'

The calling method's class, reactor.netty.transport.ServerTransport$DisposableBind, was loaded from the following location:

    jar:file:/home/blling/Documents/Projects/e-shop/infrastructure/gateway/target/gateway.jar!/BOOT-INF/lib/reactor-netty-core-1.0.20.jar!/reactor/netty/transport/ServerTransport$DisposableBind.class

The called method's class, reactor.core.publisher.MonoSink, is available from the following locations:

    jar:file:/home/blling/Documents/Projects/e-shop/infrastructure/gateway/target/gateway.jar!/BOOT-INF/lib/reactor-core-3.4.10.jar!/reactor/core/publisher/MonoSink.class

The called method's class hierarchy was loaded from the following locations:

    reactor.core.publisher.MonoSink: jar:file:/home/blling/Documents/Projects/e-shop/infrastructure/gateway/target/gateway.jar!/BOOT-INF/lib/reactor-core-3.4.10.jar!/


Action:

Correct the classpath of your application so that it contains compatible versions of the classes reactor.netty.transport.ServerTransport$DisposableBind and reactor.core.publisher.MonoSink
```

How to make `gateway` work?

**Comment by blling** [comment]
the final packaged libs in `BOOT-INF/lib`:
```shell
/home/blling/Desktop/lib/accessors-smart-2.4.8.jar
/home/blling/Desktop/lib/antlr-2.7.7.jar
/home/blling/Desktop/lib/antlr-runtime-3.4.jar
/home/blling/Desktop/lib/asm-9.1.jar
/home/blling/Desktop/lib/aspectjrt-1.9.7.jar
/home/blling/Desktop/lib/aspectjweaver-1.9.7.jar
/home/blling/Desktop/lib/bcpkix-jdk15on-1.68.jar
/home/blling/Desktop/lib/bcprov-jdk15on-1.68.jar
/home/blling/Desktop/lib/brave-5.13.9.jar
/home/blling/Desktop/lib/brave-context-slf4j-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-http-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-httpasyncclient-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-httpclient-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-jms-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-kafka-clients-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-kafka-streams-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-messaging-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-mongodb-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-rpc-5.13.9.jar
/home/blling/Desktop/lib/brave-instrumentation-spring-rabbit-5.13.9.jar
/home/blling/Desktop/lib/brave-propagation-aws-0.21.3.jar
/home/blling/Desktop/lib/classmate-1.5.1.jar
/home/blling/Desktop/lib/commons-codec-1.15.jar
/home/blling/Desktop/lib/commons-collections4-4.4.jar
/home/blling/Desktop/lib/commons-configuration-1.10.jar
/home/blling/Desktop/lib/commons-jxpath-1.3.jar
/home/blling/Desktop/lib/commons-lang3-3.12.0.jar
/home/blling/Desktop/lib/commons-lang-2.6.jar
/home/blling/Desktop/lib/commons-math-2.2.jar
/home/blling/Desktop/lib/content-type-2.2.jar
/home/blling/Desktop/lib/eureka-client-1.10.17.jar
/home/blling/Desktop/lib/eureka-core-1.10.17.jar
/home/blling/Desktop/lib/evictor-1.0.0.jar
/home/blling/Desktop/lib/gson-2.9.0.jar
/home/blling/Desktop/lib/guava-19.0.jar
/home/blling/Desktop/lib/guice-4.1.0.jar
/home/blling/Desktop/lib/HdrHistogram-2.1.12.jar
/home/blling/Desktop/lib/hibernate-validator-6.2.3.Final.jar
/home/blling/Desktop/lib/httpclient-4.5.13.jar
/home/blling/Desktop/lib/httpcore-4.4.15.jar
/home/blling/Desktop/lib/jackson-annotations-2.13.2.jar
/home/blling/Desktop/lib/jackson-core-2.13.2.jar
/home/blling/Desktop/lib/jackson-databind-2.13.2.2.jar
/home/blling/Desktop/lib/jackson-datatype-jdk8-2.13.2.jar
/home/blling/Desktop/lib/jackson-datatype-jsr310-2.13.2.jar
/home/blling/Desktop/lib/jackson-module-parameter-names-2.13.2.jar
/home/blling/Desktop/lib/jakarta.annotation-api-1.3.5.jar
/home/blling/Desktop/lib/jakarta.validation-api-2.0.2.jar
/home/blling/Desktop/lib/javax.annotation-api-1.3.2.jar
/home/blling/Desktop/lib/javax.inject-1.jar
/home/blling/Desktop/lib/jboss-logging-3.4.3.Final.jar
/home/blling/Desktop/lib/jcip-annotations-1.0-1.jar
/home/blling/Desktop/lib/jettison-1.4.0.jar
/home/blling/Desktop/lib/joda-time-2.3.jar
/home/blling/Desktop/lib/json-smart-2.4.8.jar
/home/blling/Desktop/lib/jsr305-3.0.2.jar
/home/blling/Desktop/lib/jsr311-api-1.1.1.jar
/home/blling/Desktop/lib/jul-to-slf4j-1.7.36.jar
/home/blling/Desktop/lib/kafka-clients-3.1.1.jar
/home/blling/Desktop/lib/lang-tag-1.6.jar
/home/blling/Desktop/lib/LatencyUtils-2.0.3.jar
/home/blling/Desktop/lib/log4j-api-2.17.2.jar
/home/blling/Desktop/lib/log4j-to-slf4j-2.17.2.jar
/home/blling/Desktop/lib/logback-classic-1.2.11.jar
/home/blling/Desktop/lib/logback-core-1.2.11.jar
/home/blling/Desktop/lib/logstash-logback-encoder-7.1.1.jar
/home/blling/Desktop/lib/lombok-1.18.24.jar
/home/blling/Desktop/lib/lz4-java-1.8.0.jar
/home/blling/Desktop/lib/micrometer-core-1.9.1.jar
/home/blling/Desktop/lib/mxparser-1.2.2.jar
/home/blling/Desktop/lib/netflix-eventbus-0.3.0.jar
/home/blling/Desktop/lib/netflix-infix-0.3.0.jar
/home/blling/Desktop/lib/netty-buffer-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-codec-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-codec-dns-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-codec-http2-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-codec-http-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-codec-socks-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-common-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-handler-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-handler-proxy-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-resolver-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-resolver-dns-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-resolver-dns-classes-macos-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-resolver-dns-native-macos-4.1.78.Final-osx-x86_64.jar
/home/blling/Desktop/lib/netty-transport-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-transport-classes-epoll-4.1.78.Final.jar
/home/blling/Desktop/lib/netty-transport-native-epoll-4.1.78.Final-linux-x86_64.jar
/home/blling/Desktop/lib/netty-transport-native-unix-common-4.1.78.Final.jar
/home/blling/Desktop/lib/nimbus-jose-jwt-9.22.jar
/home/blling/Desktop/lib/oauth2-oidc-sdk-9.35.jar
/home/blling/Desktop/lib/reactive-streams-1.0.4.jar
/home/blling/Desktop/lib/reactor-core-3.4.10.jar
/home/blling/Desktop/lib/reactor-extra-3.4.8.jar
/home/blling/Desktop/lib/reactor-netty-core-1.0.20.jar
/home/blling/Desktop/lib/reactor-netty-http-1.0.20.jar
/home/blling/Desktop/lib/resilience4j-annotations-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-circuitbreaker-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-circularbuffer-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-consumer-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-core-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-framework-common-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-micrometer-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-ratelimiter-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-reactor-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-retry-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-spring-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-spring-boot2-1.7.0.jar
/home/blling/Desktop/lib/resilience4j-timelimiter-1.7.0.jar
/home/blling/Desktop/lib/servo-core-0.12.21.jar
/home/blling/Desktop/lib/slf4j-api-1.7.36.jar
/home/blling/Desktop/lib/snakeyaml-1.30.jar
/home/blling/Desktop/lib/snappy-java-1.1.8.4.jar
/home/blling/Desktop/lib/spring-aop-5.3.21.jar
/home/blling/Desktop/lib/spring-beans-5.3.21.jar
/home/blling/Desktop/lib/spring-boot-2.7.1.jar
/home/blling/Desktop/lib/spring-boot-actuator-2.7.1.jar
/home/blling/Desktop/lib/spring-boot-actuator-autoconfigure-2.7.1.jar
/home/blling/Desktop/lib/spring-boot-autoconfigure-2.7.1.jar
/home/blling/Desktop/lib/spring-boot-jarmode-layertools-2.7.1.jar
/home/blling/Desktop/lib/spring-cloud-bus-3.1.2.jar
/home/blling/Desktop/lib/spring-cloud-circuitbreaker-resilience4j-2.1.3.jar
/home/blling/Desktop/lib/spring-cloud-commons-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-config-client-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-context-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-function-context-3.2.5.jar
/home/blling/Desktop/lib/spring-cloud-function-core-3.2.5.jar
/home/blling/Desktop/lib/spring-cloud-gateway-server-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-loadbalancer-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-netflix-eureka-client-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-sleuth-api-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-sleuth-autoconfigure-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-sleuth-brave-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-sleuth-instrumentation-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-sleuth-zipkin-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-bootstrap-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-bus-kafka-3.1.2.jar
/home/blling/Desktop/lib/spring-cloud-starter-circuitbreaker-reactor-resilience4j-2.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-config-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-gateway-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-loadbalancer-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-netflix-eureka-client-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-sleuth-3.1.3.jar
/home/blling/Desktop/lib/spring-cloud-starter-stream-kafka-3.2.4.jar
/home/blling/Desktop/lib/spring-cloud-stream-3.2.4.jar
/home/blling/Desktop/lib/spring-cloud-stream-binder-kafka-3.2.4.jar
/home/blling/Desktop/lib/spring-cloud-stream-binder-kafka-core-3.2.4.jar
/home/blling/Desktop/lib/spring-context-5.3.21.jar
/home/blling/Desktop/lib/spring-context-support-5.3.21.jar
/home/blling/Desktop/lib/spring-core-5.3.21.jar
/home/blling/Desktop/lib/spring-expression-5.3.21.jar
/home/blling/Desktop/lib/spring-integration-core-5.5.13.jar
/home/blling/Desktop/lib/spring-integration-jmx-5.5.13.jar
/home/blling/Desktop/lib/spring-integration-kafka-5.5.13.jar
/home/blling/Desktop/lib/spring-jcl-5.3.21.jar
/home/blling/Desktop/lib/spring-kafka-2.8.7.jar
/home/blling/Desktop/lib/spring-messaging-5.3.21.jar
/home/blling/Desktop/lib/spring-retry-1.3.3.jar
/home/blling/Desktop/lib/spring-security-config-5.7.2.jar
/home/blling/Desktop/lib/spring-security-core-5.7.2.jar
/home/blling/Desktop/lib/spring-security-crypto-5.7.2.jar
/home/blling/Desktop/lib/spring-security-oauth2-client-5.7.2.jar
/home/blling/Desktop/lib/spring-security-oauth2-core-5.7.2.jar
/home/blling/Desktop/lib/spring-security-oauth2-jose-5.7.2.jar
/home/blling/Desktop/lib/spring-security-oauth2-resource-server-5.7.2.jar
/home/blling/Desktop/lib/spring-security-rsa-1.0.10.RELEASE.jar
/home/blling/Desktop/lib/spring-security-web-5.7.2.jar
/home/blling/Desktop/lib/spring-tx-5.3.21.jar
/home/blling/Desktop/lib/spring-web-5.3.21.jar
/home/blling/Desktop/lib/spring-webflux-5.3.21.jar
/home/blling/Desktop/lib/stax2-api-4.2.1.jar
/home/blling/Desktop/lib/stringtemplate-3.2.1.jar
/home/blling/Desktop/lib/tomcat-embed-el-9.0.64.jar
/home/blling/Desktop/lib/typetools-0.6.2.jar
/home/blling/Desktop/lib/vavr-0.10.2.jar
/home/blling/Desktop/lib/vavr-match-0.10.2.jar
/home/blling/Desktop/lib/woodstox-core-6.2.1.jar
/home/blling/Desktop/lib/xmlpull-1.1.3.1.jar
/home/blling/Desktop/lib/xstream-1.4.18.jar
/home/blling/Desktop/lib/zipkin-2.23.2.jar
/home/blling/Desktop/lib/zipkin-reporter-2.16.3.jar
/home/blling/Desktop/lib/zipkin-reporter-brave-2.16.3.jar
/home/blling/Desktop/lib/zipkin-reporter-metrics-micrometer-2.16.3.jar
/home/blling/Desktop/lib/zipkin-sender-activemq-client-2.16.3.jar
/home/blling/Desktop/lib/zipkin-sender-amqp-client-2.16.3.jar
/home/blling/Desktop/lib/zipkin-sender-kafka-2.16.3.jar
/home/blling/Desktop/lib/zstd-jni-1.5.0-4.jar
```

**Comment by blling** [comment]
Error stack:
```
2022-07-01 14:45:26.858  INFO [api-gateway,,] 291475 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application API-GATEWAY with eureka with status UP
2022-07-01 14:45:26.862  INFO [api-gateway,,] 291475 --- [           main] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1656657926862, current=UP, previous=STARTING]
2022-07-01 14:45:26.863  WARN [api-gateway,,] 291475 --- [           main] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter
2022-07-01 14:45:26.957  INFO [api-gateway,,] 291475 --- [nfoReplicator-0] reactor.Mono.OnErrorResume.1             : onSubscribe(FluxOnErrorResume.ResumeSubscriber)
2022-07-01 14:45:26.972  INFO [api-gateway,,] 291475 --- [nfoReplicator-0] reactor.Mono.OnErrorResume.1             : request(unbounded)
2022-07-01 14:45:27.091 DEBUG [api-gateway,,] 291475 --- [           main] o.s.c.g.filter.GatewayMetricsFilter      : New routes count: 0
2022-07-01 14:45:27.109  INFO [api-gateway,,] 291475 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Creating binder: kafka
2022-07-01 14:45:27.310  WARN [api-gateway,,] 291475 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

java.lang.NoSuchMethodError: 'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.<init>(HttpClientConnect.java:330)
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:273)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4361)
        at reactor.core.publisher.Mono.block(Mono.java:1705)
        at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:174)
        at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:170)
        at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:151)
        at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:141)
        at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:130)
        at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1440)
        at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
        at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-07-01 14:45:27.343  INFO [api-gateway,,] 291475 --- [nfoReplicator-0] reactor.Mono.OnErrorResume.2             : onSubscribe(FluxOnErrorResume.ResumeSubscriber)
```

**Comment by hdimitrieski** [comment]
Updating reactor-core to 3.4.19 fixed the issue. :)
